name: Delete Tags

on:
  workflow_dispatch: # Manually triggered

jobs:
  delete_tags:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure all tags are fetched

      # Step 2: Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      # Step 3: Authenticate with GitHub
      - name: Authenticate with GitHub
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
      # Step 4: Fetch all tags
      - name: Fetch all tags
        run: |
          git fetch --tags

      # Step 5: List and delete tags starting with "dev"
      - name: List and Delete Tags
        run: |
          echo "Fetching tags starting with 'dev'"
          dev_tags=$(git tag -l 'dev-1.0.0*')
          
          if [ -z "$dev_tags" ]; then
            echo "No tags found starting with 'dev'"
            exit 0
          fi

          for tag in $dev_tags; do
            echo "Deleting tag $tag"
            git push --delete origin "$tag" || echo "Failed to delete remote tag $tag"
            git tag -d "$tag" || echo "Failed to delete local tag $tag"
          done
